### ISSUE TITLE
subject not able to add

### ISSUE THREAD

**Issue by SanjanaPriyadarshini** [SanjanaPriyadarshini/Test#1]
**1. Version**  :   V1.0

2. Reproduction link : http://dev.testfreshers.com/profile

3. Steps to reproduce :   
      1. login with trainer/Qadder  
      2. click on add subject
      **3. enter details and click on save** 

4. What is expected ? :
        should able to create subject

5. What is actually happening? : 
          not able to add throwing error 
credentials : spoorti@t.com, 123455667

**Comment by spoortinaik** [comment]
fixed

**Comment by SanjanaPriyadarshini** [comment]
okay working
